variables:
  SHARED_LIBS: "ON"
  SECURE_LOG_LEVEL: "debug"

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml


stages:
  - build
  - test

.build-job-ubuntu-22:
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y gcc g++ cmake wget git
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS='$SHARED_LIBS' -B "build/" 
    - cmake --build build/ --config Release
    - pushd python
    - python setup.py build
    - popd

build-job-ubuntu-22-shared-libs-on:
  extends: .build-job-ubuntu-22
  stage: build
  variables:
    SHARED_LIBS: "ON"

build-job-ubuntu-22-shared-libs-off:
  extends: .build-job-ubuntu-22
  stage: build
  variables:
    SHARED_LIBS: "OFF"


.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS="$SHARED_LIBS" -B "./build"
    - cmake --build ./build --config Release

windows-shared-on:
  extends:
    - .windows_job
  stage: build
  variables:
    SHARED_LIBS: "OFF"

windows-shared-off:
  extends:
    - .windows_job
  stage: build
  variables:
    SHARED_LIBS: "ON"