stages:
  - build

.install-packages:
    script:
        - sudo apt-get install -y gcc g++ cmake wget git

build-job-ubuntu-22:
  extends: .install-packages
  image: ubuntu:22.04
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."